### ISSUE TITLE
Feature request: gitlab support

### ISSUE THREAD

**Issue by theguly** [seanbreckenridge/oh-my-stars#2]
did you ever thinked about adding gitlab support?
lately we see lot of new project spanning between the two companies.

if you are interested i can try to work out a PR

**Comment by purarue** [comment]
Hmm -- for a bit of context on the current state of things here... Am not totally comfortable with how the tinydb database works here, so adding a bunch of code to interact with an additional API isn't something I see myself maintaining for years to come

Would likely require a substantial redesign (or just some sort of hack on top of the current schema to check the site before inserting/updating) since this updates by comparing to the most recent items inserted into the database, and by then we're getting further and further away from the main repo

In a perfect world I would rewrite this to support github and gitlab from the get-go, and add a [couple other features](https://github.com/wolfg1969/oh-my-stars/issues/16) (being the main reason I forked this in the first place)

For now, I don't really want to keep extending this with additional features, but perhaps [upstream](https://github.com/wolfg1969/oh-my-stars) may be willing to do so?

**Comment by theguly** [comment]
i believe upstream is dead/unmaintained.

by the way i totally see your point, let's close this issue until you or someone else have the time/will to write a new tool.

thanks for the reply man
